### ISSUE TITLE
Loading the logo.svg to the header

### ISSUE THREAD

**Issue by tronicdata** [Tokyo-Buffalo/pow-wow-calendar#13]
I am getting errors trying to load the logo from 'client/common/powLogo.svg'. I can't get it to display. I added a package for inline SVG for webpack.

**Comment by kevoneil** [comment]
Look into `svg-inline-loader`
https://webpack.js.org/loaders/svg-inline-loader/

**Comment by kevoneil** [comment]
@tronicdata Found another way, we can use this SVGR command line tool to transform our SVG files into react components. That'll makes things a lot easier. See #14

**Comment by kevoneil** [comment]
<img width="641" alt="Screen Shot 2019-11-19 at 14 55 02" src="https://user-images.githubusercontent.com/6971504/69120285-95c4b180-0adc-11ea-9ecd-421525e726ca.png">
