### ISSUE TITLE
Add Event Fields to front end

### ISSUE THREAD

**Issue by tronicdata** [Tokyo-Buffalo/pow-wow-calendar#27]
Event Fields need to be added along with corresponding model values. Maybe adding the values in the backend model should be another issue?

Event Fields:

- Title
- Date
-- Start
-- End
- Organizer
- Image Attachment (poster/flier, maybe option for photoGallery later?)
- Venue
-- Name
-- Location
- Pricing
- Tribes Represented
- Contact information
-- name
-- email
-- phone
-- website
- Details

**Comment by tronicdata** [comment]
After this issue is completed:

- Add issue to create corresponding backend model
- verify events are being recorded into the db
- add issue to have events show up on the calendar
- add issue to have 'upcoming events' display on the dashboard

Let me know if there is a better way of displaying this timeline

**Comment by kevoneil** [comment]
@tronicdata Right, let's split this up, will create some more info for events.

**Comment by kevoneil** [comment]
@tronicdata You will have the `featured_image` and `images` fields in the end.

**Comment by kevoneil** [comment]
#30 was merged in, so we can now add some more input fields to the create events form

**Comment by tronicdata** [comment]
I merged in develop, but still not sure how it is working. Will check it out more on sat
