### ISSUE TITLE
Error: Unhandled Rejection (TypeError): Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by tronicdata** [Tokyo-Buffalo/pow-wow-calendar#28]
Are you getting this too?

UserStore.setUserName
src/store/UserStore.js:22
  19 |    isLoggedIn: false
  20 |  });
  21 | 
> 22 |  setUserName({ id, name, email, username }: User) {
  23 |    if (id) {
  24 |      this.user.id = id;
  25 |    }
View compiled
App._callee$
src/components/App.js:27
  24 |          const id = decode(token).sub;
  25 |          const userDetails = await this.setUserDetails(id);
  26 | 
> 27 |          this.props.store.setUserName(userDetails);
  28 |        }
  29 | 
  30 |        setUserDetails(id) {

![error](https://user-images.githubusercontent.com/4485507/38688522-4b6921a6-3e47-11e8-9d72-49c69dcf3e2a.PNG)

**Comment by kevoneil** [comment]
@tronicdata Might have fixed it, can you double check?

Reopen if it doesn't work please.
