### ISSUE TITLE
Validate and Sanitize forms

### ISSUE THREAD

**Issue by tokyoincode** [Tokyo-Buffalo/pow-wow-calendar#3]
Validate and sanitize forms for the add-event page

**Comment by tokyoincode** [comment]
@tronicdata Found something cool, we can use this package instead. Makes validation much easier.
https://github.com/aldeed/meteor-autoform#a-basic-insert-form

Already pushed it to the develop branch. We should create a new branch and start working on adding the form.

**Comment by tronicdata** [comment]
almightypacers@larrybuff:~/Documents/coding/pow-wow-calendar$ git checkout -b issue-3-validate-forms origin/issue-3-validate-forms
fatal: Cannot update paths and switch to branch 'issue-3-validate-forms' at the same time.
Did you intend to checkout 'origin/issue-3-validate-forms' which can not be resolved as commit?
