### ISSUE TITLE
Master needs to go back one commit

### ISSUE THREAD

**Issue by tronicdata** [Tokyo-Buffalo/pow-wow-calendar#4]
I am having a lot of issues on my machine with permissions and input/output errors. I think a lot of it has to do with working on the bash system inside of windows. The last commit I did, broke some stuff, not sure what was going on. Master needs to go back one commit, I will delete and download the project again on my ubuntu laptop and see how it goes.

**Comment by tokyoincode** [comment]
@tronicdata What was happening exactly? I'm going to have to push to the master branch again and test it out on my Mac. Did you get it working in the end?

**Comment by tokyoincode** [comment]
@tronicdata Reverted
